# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dictionary.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'dictionary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64ictionary.proto\"\x0e\n\x0c\x45mptyRequest\"\x19\n\tLineReply\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x7f\n\x10\x41llConceptsReply\x12\x37\n\x0b\x64\x65\x66initions\x18\x01 \x03(\x0b\x32\".AllConceptsReply.DefinitionsEntry\x1a\x32\n\x10\x44\x65\x66initionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"h\n\tListReply\x12*\n\x08\x63oncepts\x18\x01 \x03(\x0b\x32\x18.ListReply.ConceptsEntry\x1a/\n\rConceptsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"!\n\x11\x44\x65\x66initionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"&\n\x0f\x44\x65\x66initionReply\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\"2\n\rCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"0\n\rCompleteReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xef\x02\n\nDictionary\x12$\n\x05\x41\x62out\x12\r.EmptyRequest\x1a\n.LineReply\"\x00\x12%\n\x06\x41uthor\x12\r.EmptyRequest\x1a\n.LineReply\"\x00\x12\x31\n\x0b\x41llConcepts\x12\r.EmptyRequest\x1a\x11.AllConceptsReply\"\x00\x12#\n\x04List\x12\r.EmptyRequest\x1a\n.ListReply\"\x00\x12\x34\n\nDefinition\x12\x12.DefinitionRequest\x1a\x10.DefinitionReply\"\x00\x12*\n\x06\x43reate\x12\x0e.CreateRequest\x1a\x0e.CompleteReply\"\x00\x12*\n\x06Update\x12\x0e.CreateRequest\x1a\x0e.CompleteReply\"\x00\x12.\n\x06Remove\x12\x12.DefinitionRequest\x1a\x0e.CompleteReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dictionary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALLCONCEPTSREPLY_DEFINITIONSENTRY']._loaded_options = None
  _globals['_ALLCONCEPTSREPLY_DEFINITIONSENTRY']._serialized_options = b'8\001'
  _globals['_LISTREPLY_CONCEPTSENTRY']._loaded_options = None
  _globals['_LISTREPLY_CONCEPTSENTRY']._serialized_options = b'8\001'
  _globals['_EMPTYREQUEST']._serialized_start=20
  _globals['_EMPTYREQUEST']._serialized_end=34
  _globals['_LINEREPLY']._serialized_start=36
  _globals['_LINEREPLY']._serialized_end=61
  _globals['_ALLCONCEPTSREPLY']._serialized_start=63
  _globals['_ALLCONCEPTSREPLY']._serialized_end=190
  _globals['_ALLCONCEPTSREPLY_DEFINITIONSENTRY']._serialized_start=140
  _globals['_ALLCONCEPTSREPLY_DEFINITIONSENTRY']._serialized_end=190
  _globals['_LISTREPLY']._serialized_start=192
  _globals['_LISTREPLY']._serialized_end=296
  _globals['_LISTREPLY_CONCEPTSENTRY']._serialized_start=249
  _globals['_LISTREPLY_CONCEPTSENTRY']._serialized_end=296
  _globals['_DEFINITIONREQUEST']._serialized_start=298
  _globals['_DEFINITIONREQUEST']._serialized_end=331
  _globals['_DEFINITIONREPLY']._serialized_start=333
  _globals['_DEFINITIONREPLY']._serialized_end=371
  _globals['_CREATEREQUEST']._serialized_start=373
  _globals['_CREATEREQUEST']._serialized_end=423
  _globals['_COMPLETEREPLY']._serialized_start=425
  _globals['_COMPLETEREPLY']._serialized_end=473
  _globals['_DICTIONARY']._serialized_start=476
  _globals['_DICTIONARY']._serialized_end=843
# @@protoc_insertion_point(module_scope)
